name: update values

# Controls when the action will run.
on:
  workflow_dispatch:
  schedule:
   - cron:  '0 */6 * * *'

jobs: 
  scrap_Viminale:
    # The type of runner that the job will run on
    runs-on: macos-latest

    env:
      TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}

    # Load repo and install R
    steps:
    - uses: actions/checkout@master
    - uses: r-lib/actions/setup-r@master

    # Set-up R
    - name: Install packages
      run: |
        R -e 'install.packages(c("stringr", "here", "httr", "jsonlite", "tibble", "progress", "httpuv"))'
    - name: Install old rtweet
      run: |
        R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/rtweet/rtweet_0.7.0.tar.gz", repos=NULL, type="source", dependencies=T)'
    # Run R script
    - name: scrap
      run: Rscript script/profughiUcraina.R
     
 # Add new files in data folder, commit along with other modified files, push
    - name: Commit files
      run: |
          echo "Checking data on: `date`"
          if [ -n "$(git status --porcelain)" ]; then
            echo "New update available"
            git config --local user.name actions-user
            git config --local user.email "actions@github.com"
            git add data/*
            git commit -am "Update data - $(date)"
            git push origin main
          else
            echo "no changes to commit"
          fi
      env:
        TZ: Europe/Rome